### ISSUE TITLE
Add autoload macro for intaractive functions

### ISSUE THREAD

**Issue by casch-at** [xenodium/chatgpt-shell#215]
Hi,

it's common practice to add the `;;;###autoload` macro (correct term?) to interactive functions. I would like to create a PR if you are open to this change.

Thank you for this package!

Best regards,  
Christian

**Comment by xenodium** [comment]
Thanks for reaching out! 

> I would like to create a PR if you are open to this change.

Sure! Did you have some interactive functions in mind? Initially it was only added for the entry point to the package (`chatgpt-shell` interactive function), but there are other entry points that have been introduced since.

Examples: `chatgpt-shell-prompt-compose`, `chatgpt-shell-describe-image`, `chatgpt-shell-describe-code` (there are more).

We can prolly continue with the "entry point" criteria as all other functions would have gone through entry points.

> Unless it doesn't make sense as it is the case for chatgpt-shell-swap-system-prompt...

Maybe not this one, since you have to be in a shell to use it (already past entry point). These can be usually spotted as they have `(user-error "Not in a shell")`.

> Thank you for this package!

Glad you like it.

**Comment by casch-at** [comment]
@xenodium PR is up, see #216.

Seems like I missed some 🙈.

**Comment by xenodium** [comment]
Nevermind, you're one step ahead of me... I see your PR #216 with some entry points already. I merged https://github.com/xenodium/chatgpt-shell/commit/fce2b6d3609135f827da46dbb6d1f37d65a8b024

**Comment by xenodium** [comment]
> Seems like I missed some 🙈.

Leave it up to you if you want to handle those also.

**Comment by xenodium** [comment]
Added a few more in https://github.com/xenodium/chatgpt-shell/commit/63adf342822627482677c0591846fb98002e429a. I think this does most entry points. Gonna close issue. Please reopen if there are more you reckon we should add.
