### ISSUE TITLE
Symbol’s function definition is void: json-available-p

### ISSUE THREAD

**Issue by jacquesdurden** [xenodium/chatgpt-shell#24]
Since the last modifications, I got the error message written in the title. I see in the code that it's now recommended to have built emacs with the json support, that is, "Emacs needs to be compiled with --with-json". 

Is it possible to go back to a minimal config of chatgpt-shell.el if this is not the case, by switching off certain options requiring json? Thank you.

**Comment by xenodium** [comment]
Sorry about that. The check can be smarter. Will fix.Can you share a bit more about your setup? Emacs version and flags built with?On 27 Mar 2023, at 08:15, jacquesdurden ***@***.***> wrote:﻿
Since the last modifications, I got the error message written in the title. I see in the code that it's now recommended to have built emacs with the json support, that is, "Emacs needs to be compiled with --with-json".
Is it possible to go back to a minimal config of chatgpt-shell.el if this is not the case, by switching off certain options requiring json? Thank you.

**Comment by jacquesdurden** [comment]
Great, thank you. I'll test it asap.

**Comment by jacquesdurden** [comment]
I've just tested it under GNU Emacs 27.2 on Mac (w/o json) but I get no prompt with a single message "CHATGPT: no process"

**Comment by xenodium** [comment]
I've built 27.2 on macOS and it seems to be working ok

<img width="796" alt="Screenshot 2023-03-28 at 22 27 00" src="https://user-images.githubusercontent.com/8107219/228370727-57da5009-1354-47f5-922c-5fa368d57266.png">

Could you restart your Emacs instance, if you haven't?
